ProEpiDesenvolvimento/guardioes-api

- app/controllers/registration_controller.rb
- app/models/manager.rb
- app/serializers/user_serializer.rb
Adicionei os parametros de cidade e estado no serializer de usuário;<br>
**Checklist**
> Mudanças no serializer

- docker-compose.yml
> Fixes docker-compose

- app/controllers/surveys_controller.rb
- config/routes.rb
Criei uma rota que renderiza o surveys criados na ultima semana;<br>
**Checklist**
> Added method to render all of the last week surveys

- docker-compose.yml
Reverts proepidesenvolvimento/guardioes-api#24
> Revert "Fixes docker-compose"

- app/controllers/registration_controller.rb
- app/models/school_unit.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- db/migrate/20200604024321_add_school_unit_id_to_user.rb
- db/schema.rb
> added school unit on user

- app/controllers/surveys_controller.rb
- app/models/survey.rb
- app/serializers/survey_without_user_serializer.rb
- app/serializers/user_without_name_serializer.rb
Novo serializer para renderizar user sem nomes a afins;<br>
**Checklist**
> added serializer for user

- Dockerfile
- app/controllers/surveys_controller.rb
- app/serializers/survey_without_user_serializer.rb
- app/serializers/user_without_name_serializer.rb
- config/database.yml
- default.conf
- docker-compose.yml
- update.sh
Reverts proepidesenvolvimento/guardioes-api#44
> Revert "Development"

- app/controllers/surveys_controller.rb
Reparos no survey controller
**Checklist**
> last 12h surveys

- app/controllers/users_controller.rb
- app/models/user.rb
Feitas alterações no model e controller de usuário para permitir a atualização dos seus dados.
Conserta issue #55 
**Checklist**
> Conserta bug no user update

- config/application.rb
- config/initializers/elasticsearch.rb
- docker-compose.yml
> Configure elasticsearch

- app/controllers/users_controller.rb
- app/models/user.rb
Adicionadas mensagens de erros em user update.
Associado a issue #55 
**Checklist**
> Add error messages to user update

- app/controllers/users_controller.rb
Adiciona os parametros necessários para edição de usuário no método update_params da users_controller. (#66 - @emanuks).<br>
**Checklist**
> changes update params

- app/controllers/application_controller.rb
- app/controllers/registration_controller.rb
- app/models/admin.rb
Apenas foi adicionada uma validação no método de criar admin vendo se existe um admin logado;<br>
**Checklist**
> Added authentication on admin create

- Dockerfile
- config/application.rb
- docker-compose.yml
Foi adicionado um configuração para ajustar o time zone da aplicação.<br>
**Checklist**
> Created_at with correct timezone

- app/controllers/surveys_controller.rb
This Pull Requests fix the bug in [Issue #90](https://github.com/proepidesenvolvimento/guardioes-api/issues/90) <br>
It was edited the surveys_controller so that the survey limit was applied to each user separately.   
**Checklist**
> Fix bug with reports by multiple users

- app/controllers/users_controller.rb
Adiciona o campo _País_ nos parametros de atualização do usuário<br>
**Checklist**
> Adding country to user update_params

- app/controllers/users_controller.rb
- app/mailers/user_mailer.rb
- app/models/user.rb
- config/environments/development.rb
- config/environments/production.rb
Conserta um bug que, em produção, não enviava emails para os usuários.
**Checklist**
> Fix emailer bug

- app/controllers/users_controller.rb
Conserta erro no update de senha, onde a senha não era alterada.
**Checklist**
> Fix user reset password bug

- app/controllers/households_controller.rb
- app/models/survey.rb
- app/models/user.rb
Esse PR adiciona dados que a API envia para o elastic, de forma a enviar dados que seriam custosos (em performance) de se conseguir no kibana. Além disso, conserta problemas com a API não dando update numa linha quando um recurso é alterado.
**Checklist**
> Fix elastic communication

- app/models/survey.rb
- app/models/user.rb
Conserta bug com o envio de dados da API para a base dados do elasticsearch.
**Checklist**
> Fix kibana data upload bug

- app/controllers/data_visualization_controller.rb
- config/routes.rb
- spec/controllers/data_visualization_controller_spec.rb
Certos dados chaves (número de usuários, número surveys com e sem sintomas) serão extraído da API para serem consumidos por outras páginas web para demonstrar o impacto do aplicativo.
Resolve a extração de dados para issue [#47](https://github.com/proepidesenvolvimento/guardioes-web/issues/47) do guardioes-web.
**Checklist**
> Add data visualization endpoints

- app/controllers/groups_controller.rb
- Abri as permissões da rota para qualquer usuário.
- Mudei o estilo de retorno do handle para ficar mais compatível com o resto da API.
**Checklist**
> get_twitter route fix

- README.md
- app/models/group.rb
Para diminuir a carga de trabalho (e potenciais bugs como consequência) de se levantar o ambiente, tanto de produção quanto de desenvolvimento, esse PR remove a necessidade de fazer o setup da classe Group, que já vem funcional assim que utilizada pela primeira vez.
**Checklist**
> Remove group setup

- app/controllers/group_managers_controller.rb
- app/controllers/registration_controller.rb
- app/controllers/symptoms_controller.rb
This PR creates the CRUD for managers. Closes the issues #144 and #143 <br>
**Checklist**
> Create crud for managers

- app/models/survey.rb
- app/models/user.rb
- config/application.rb
Separa os dados por nome de indice para ser utilizado nos dashboards de instituições.
Esta issue é pre-condição para o funcionamento [dessa outra issue](https://github.com/proepidesenvolvimento/guardioes-web/issues/64).
**Checklist**
> Elastic index pattern data segregation

- app/controllers/registration_controller.rb
Corrige o erro de não receber a versão de compilação mais recente dos Termos e Políticas no app na hora do cadastro.<br>
**Checklist**
> Adiciona o atributo policy_version na registration_controller.rb

- app/controllers/group_managers_controller.rb
- app/mailers/vigilance_mailer.rb
- app/models/survey.rb
- app/serializers/group_manager_serializer.rb
- db/migrate/20200924013233_add_vigilance_email_to_group_managers.rb
- db/schema.rb
Changes the recipient email for vigilance mailer.<br>
> Changes the recipient email for vigilance mailer

- app/controllers/users_controller.rb
- config/routes.rb
- db/schema.rb
O método de update tem autenticação apenas para Users, foi adicionado um novo método `admin_update` para que os administradores possam editar usuários também;<br>
**Checklist**
> Calling method to only admin update user

- db/migrate/20200624190816_create_messages.rb
Por decorrência do sistema de vigilância ativa, um erro de migrações inconsistentes foi introduzido por alterar uma migração existente ao invés de se criar uma nova. Esse PR conserta o erro.
**Checklist**
> Fix inconsistent messages migration

- docker-compose.yml
Para fazer o teste como o servidor de homolog do metabase, essa base de dados foi criada e será carregada com os dados da antiga para funcionar como réplica, sem correr grandes riscos.
**Checklist**
> Create read only postgres database

- app/serializers/content_serializer.rb
Adicionei created_at e updated_at no serializer de content;<br>
**Checklist**
> Added created and updated at on serializer

- app/controllers/application_controller.rb
- app/controllers/managers_controller.rb
- app/models/ability.rb
- db/schema.rb
Corrigir problema onde User não tinha permissões para acessar algumas telas do APP, como por exemplo, Usuário não tinha permissão para editar o próprio perfil pelo aplicativo.<br>
**Checklist**
> fix user permissions for app

- app/models/ability.rb
- db/migrate/20201118173733_remove_permission_id_from_manager.rb
- db/schema.rb
Corrigido bug nas que não achava as permissões<br>
**Checklist**
> fix bug with permissions

- app/controllers/application_controller.rb
- app/controllers/contents_controller.rb
- app/controllers/group_managers_controller.rb
- app/controllers/managers_controller.rb
- app/controllers/symptoms_controller.rb
- app/controllers/syndromes_controller.rb
- app/controllers/users_controller.rb
- app/models/ability.rb
- db/schema.rb
Este PR resolve a issue #153 do repo guardioes-web.
> Fix permission file

- app/serializers/admin_serializer.rb
Adds first_name and last_name to admin serializer<br>
**Checklist**
> Returns admin name

- app/serializers/syndrome_serializer.rb
- db/schema.rb
O serializer de Síndromes foi adicionado alguns atributos para permitir a edição correta no painel.<br>
**Checklist**
> Fix Syndrome edition

- app/controllers/group_managers_controller.rb
- app/controllers/users_controller.rb
- app/models/ability.rb
Resolve problemas de indentação no código.
> Fix permission

- app/controllers/managers_controller.rb
- app/serializers/group_manager_serializer.rb
Este PR edita a controller de Manager para retornar as permissões de um gerente e para que deixe possível a edição da mesma.<br>
1) Veja se as permissões estão sendo retornadas na rota GET de Managers.
2) Edite essas permissões passando um parâmetro "permissões", como no exemplo abaixo:
"permissões": ["user", "content"] onde os valores do array são as permissões do Manager.
> Managers Permissions

- app/models/ability.rb
**Descrição**
Resolve o problema de permissões para o usuário do aplicativo
> Fix user app permission

- app/models/ability.rb
Corrige os problemas com as permissões para o usuário do app e Manager
> Fix manager and user permissions

- app/models/survey.rb
Resolve o problema de match de sindrome. Em um survey o sintoma vai como o "code", para verificar a sindrome era usado o "descripton"
> Fix match syndrome

- app/controllers/managers_controller.rb
- app/models/ability.rb
- db/schema.rb
Corrige as permissões para que cada tipo de user sem permissão possa editar pelo menos a si próprio.<br>
Usando a branch *feature/profile* do repositório guardioes-web, testar a edição de perfil de cada tipo de user na aba "Conta". Pode se usar o Postman com token do próprio usuário também.
Admin, Manager e Group Manager podendo serem editados.
**Checklist**
> Fix Admin, Manager and Group Manager permissions

- app/controllers/registration_controller.rb
- app/models/survey.rb
Este PR faz a verificação do atributo grupo do usuário quando o mesmo realiza um bad report. A verificação não acontecia e quando o atributo group não existia ocorria um erro na api.<br>
Realize um bad report com um usuário que não possua grupo cadastrado.
É esperado que o report aconteça normalmente.
> Conserta erro ao realizar um bad report

- app/controllers/admins_controller.rb
- app/controllers/managers_controller.rb
- config/routes.rb
Admin/Manager controllers e routes.rb editadas para funcionar os métodos de edição de senha.<br>
Testar rotas de recuperação de senha.
Os usuários Admin e Managers conseguirem editar a senha.
**Checklist**
> Fix Admin and Manager password reset

- Gemfile
- app/controllers/group_managers_controller.rb
- app/models/survey.rb
- app/serializers/group_manager_serializer.rb
- app/serializers/survey_serializer.rb
- db/migrate/20210106193804_add_godata_credentials_to_group_manager.rb
- db/migrate/20210108224224_add_syndrome_id_to_survey.rb
Adiciona os atributos username_go_data e password_go_data a Group Manager<br>
Adiciona o campo syndrome_id a Survey<br>
Reporta um caso no surto do Group Manager quando o survey possui os sintomas de uma síndrome da vigilância ativa que está conectada com o GoData do GM
> Faz a integração com o GoData

- app/models/survey.rb
- app/serializers/group_manager_serializer.rb
Este PR conserta alguns bugs na integração com o GoData.<br>
> Conserta alguns bugs na integração com o GoData

- app/controllers/group_managers_controller.rb
- app/models/survey.rb
Conserta os campos sintomas, endereço e gênero nos dados do caso do godata.<br>
> Conserta alguns campos do caso do godata

- Gemfile.lock
- app/controllers/group_managers_controller.rb
> fix encryptor

- app/controllers/groups_controller.rb
- app/serializers/group_simple_serializer.rb
- docker-compose.yml
Add permit and serializer for new params in group table
> Add permit and serializer for new params in group table

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/models/ability.rb
- app/models/household.rb
- app/models/user.rb
Adiciona um método para os City Managers retornar todos os usuários de um município, utilizando ou não o email na query.
Faça login como City Manager e utilize a rota ```/user/panel``` ou  ```/user/panel?email=``` para obter os usuários.
Retornar os usuários apenas daquele município.
**Checklist**
> Add City Manager methods and route

- app/controllers/groups_controller.rb
Resolve a issue [#221](https://github.com/proepidesenvolvimento/guardioes-app/issues/211).
> Previne a criação de Group com parent_id = nil

- app/controllers/city_managers_controller.rb
- app/controllers/registration_controller.rb
- app/models/ability.rb
- app/models/city_manager.rb
Corrige as permissões que os `Admin` e `Manager` possuem sobre os `City Managers`.<br>
Vendo os casos de teste da issue #268.
As permissões funcionarem corretamente.
**Checklist**
> Fix permissions to City Managers

- app/models/survey.rb
Corrige o endereço mandado para o GoData
> fix send address for godata

- app/controllers/data_visualization_controller.rb
Esse PR adiciona o gerenciamento do parâmetro para a API aumentando a segurança do sistema.
**Checklist**
> Changes the responsibility of metabase panel 2 api

- app/controllers/admins_controller.rb
- app/controllers/application_controller.rb
- app/controllers/city_managers_controller.rb
- app/controllers/contents_controller.rb
- app/controllers/group_managers_controller.rb
- app/controllers/groups_controller.rb
- app/controllers/managers_controller.rb
- app/controllers/registration_controller.rb
- app/controllers/symptoms_controller.rb
- app/controllers/syndromes_controller.rb
- app/controllers/users_controller.rb
- app/serializers/admin_serializer.rb
- app/serializers/city_manager_serializer.rb
- app/serializers/content_serializer.rb
- app/serializers/group_manager_serializer.rb
- app/serializers/group_serializer.rb
- app/serializers/manager_serializer.rb
- app/serializers/symptom_serializer.rb
- app/serializers/syndrome_serializer.rb
- app/serializers/user_serializer.rb
- db/migrate/20210528200120_add_traceability_to_symptoms.rb
- db/migrate/20210528202702_add_traceability_to_syndromes.rb
- db/migrate/20210528203101_add_traceability_to_contents.rb
- db/migrate/20210528203124_add_traceability_to_users.rb
- db/migrate/20210528203205_add_traceability_to_admins.rb
- db/migrate/20210528203325_add_traceability_to_managers.rb
- db/migrate/20210528203529_add_traceability_to_group_managers.rb
- db/migrate/20210528203750_add_traceability_to_city_managers.rb
- db/migrate/20210528203817_add_traceability_to_groups.rb
- db/schema.rb
Adiciona as colunas created_by ,updated_by, deleted_by em algumas models e modifica os métodos na controller de cada um para atualizar esses campos.<br>
Criar, editar ou deletar os objetos das models para verificar as colunas created_by ,updated_by, deleted_by.
Atualizar o respectivo campo a cada vez que um usuário realiza uma ação nas models.
**Checklist**
> User Traceability on Models

- app/controllers/surveys_controller.rb
- app/models/survey.rb
- app/serializers/survey_serializer.rb
- app/serializers/survey_without_user_serializer.rb
- db/migrate/20210605233453_add_postal_code_to_surveys.rb
- db/schema.rb
- db/seeds.rb
Foi adicionado o campo de postal_code na model de surveys, e adicionado também nas controllers de surveys e surveys_without_user para disponibilização nas rotas.
* Consulte a tabela de surveys no banco de dados e verifique a presença da coluna de survey.
* Crie um survey com localização e verifique se ele conseguiu obter o postal code.
* Faça requisições para verificar se o objeto survey vem corretamente. 
A api deve ser capaz de armazenar o campo de postal_code, obter a partir de coordenadas e retornar corretamente esse dado nas rotas corretas. 
**Checklist**
> Adicionando campo de postal_code

- app/controllers/group_managers_controller.rb
- app/serializers/group_manager_serializer.rb
- db/migrate/20210621213948_add_url_go_data_to_group_managers.rb
- db/schema.rb
Adiciona a coluna `url_godata` para os GroupManagers e modifica o serializer e controller.<br>
Editar ou criar um GroupManager passando um valor para o `url_godata`, e testar página do painel.
Ser possível definir um valor para o `url_godata`.
**Checklist**
> Fix Go.Data URL

- app/controllers/surveys_controller.rb
- app/models/ability.rb
- app/serializers/survey_serializer.rb
- app/serializers/user_serializer.rb
- config/routes.rb
- db/migrate/20210630003630_add_reviewed_to_surveys.rb
- db/schema.rb
Esse PR adiciona uma rota para mostrar Surveys sintomáticas que deram match com alguma síndrome de Vigilância Ativa de um determinado grupo.<br>
Faça um GET na rota `surveys/group_cases` autenticado como GroupManager. Certifique se que o grupo desse GroupManager tenha usuários e esses usuários reportaram Surveys que foram identificadas com alguma Syndrome.
Retornar casos e respeitar a lógica de reincidência.
**Checklist**
> Group Survey cases route

- app/controllers/surveys_controller.rb
O cache só atualizava quando o servidor era resetado. Depois de pesquisar achei que poderia ser o arquivo de cache que precisa ser apagado.
Inicie uma sessão no app, veja o mapa, mande um survey e verifique se o survey aparece no mapa e na response da request.
**Checklist**
> Atualização automática do cache do mapa

- app/controllers/vaccines_controller.rb
- app/models/ability.rb
- app/models/app.rb
- app/models/vaccine.rb
- app/serializers/vaccine_serializer.rb
- config/routes.rb
- db/migrate/20210723034147_create_vaccine.rb
- db/migrate/20210723145258_create_vaccines.rb
- db/migrate/20210723174134_add_app_ref_to_vaccines.rb
- db/schema.rb
- spec/models/vaccine_spec.rb
Foi criado a migration, a model, validações, controller e as rotas. O CRUD de forma geral de vacinas 
Sem autentiação: Comente a linha que autentica como admin e faça uma requisição simples 
Com auteticação: Faça autenticação como admin e colete o token e o use para acessar as rotas de vacinas.
O programa deve ser capaz de retornar a(s) vacina(s) nas rotas get
Deve ser capaz de atualizar corretamente nas rotas PATCH/PUT
DEve ser capaz de apagar corretamente na rota DELETE
Deve ser capaz de criar corretamente na rota POST
**Checklist**
> CRUD de vacinas

- app/controllers/users_controller.rb
- app/models/user.rb
- app/models/vaccine.rb
- app/serializers/user_serializer.rb
- app/serializers/user_without_name_serializer.rb
- db/migrate/20210729225603_add_vaccine_fields_to_users.rb
- db/schema.rb
Foi adicionado os campos de *first_dose_date* e *second_dose_date* que representam as datas da primeira e segunda dose respectivamente. Também foi adicionado um campo *vaccine_id* que representa qual vacina foi aplicado no usuário nas doses que ele tomou. Todos esses atributos foram adicionados na tabela de usuários
Foi adicionado um relacionamento entre vacinas e usuários. Nesse caso vacinas possuem usuários. 
Faça requisições nas rotas de usuários. É esperado que as rotas de update atualizem os novos campo adicionados normalmente assim. 
Com relação as rotas do tipo get ou que retornam o usuário é esperado que o seguinte objeto seja retornado:
user: {
...user_atrubutes,
app: {...},
vaccine: {...}.
household: {...},
}
**Checklist**
> Adicionando campos sobre a vacinação na tabela de usuários.

- app/models/user.rb
Na model de usuários, a parte de *belongs_to*, foi adicionado que essa associação é opcional, assim é possível cadastrar mesmo que o usuário ainda não possua uma vacina. 
Na rota *user/signup* faça uma requisição do tipo post com o seguinte objeto:
{
"user" : {
"email" : "t2@t.com",
"user_name" : "Teste",
"password" : "12345678",
"app_id" : "1",
"gender": "m",
"race": "pardo",
"country": "Brazil",
"state": "DF",
"city": "Recanto das Emas"
}
}
A response é uma 200 indicando que o usuário foi cadastrado com sucesso. 
**Checklist**
> Making vaccine optional to sign up users

- app/models/survey.rb
Corrige bug de GroupManagers que possuem uma url do Go.Data diferente da url definida como ambiente.<br>
Reportar uma Survey sintomática utilizando um usuário que possua uma Instituilção, e , que o GroupManager dessa instituição possua uma Syndrome e todos os dados do GoData.
Os métodos de Vigilância Ativa de uma Survey funcionem
**Checklist**
> Fix GoData URL on survey.rb

- app/controllers/surveys_controller.rb
- app/controllers/syndromes_controller.rb
- app/models/survey.rb
- app/serializers/syndrome_serializer.rb
- db/migrate/20210811141836_add_threshold_score_to_syndromes.rb
- db/migrate/20210817132917_add_default_value_to_policy_version_for_users.rb
- db/schema.rb
Foi apenas feita uma migration que muda o valor padrão da coluna *policy_version* da tabela de *users*.
Verifique o valor padrão da versão das politicas de privacidade se esta conforme a versão atual.
**Checklist**
> Updating policy version

- app/controllers/form_questions_controller.rb
- app/controllers/forms_controller.rb
- app/models/form.rb
- app/models/form_question.rb
Adiciona lógicas auxiliares para edição de Form Questions e Form Options pelo painel `guardioes-web`.<br>
Utilize essa branch e a `feature/biosecurity` no repositório `guardioes-web`. Seguir as instruções do PR aberto nele.
Poder editar e criar novas Form Options, editar Form Questions existentes
**Checklist**
> Add additional logic for Forms

- app/controllers/data_visualizations_controller.rb
Adiciona a dashboard de vacinação para a rota de data_visualization.<br>
Utilizar a branch `feature/vaccineDashboard` do repositório `guardioes-web` e seguir as instruções do PR aberto lá. Necessário setar as variáveis de ambiente do metabase.
Retornar o url da Dashboard de Vacinação na rota de data_visualization.
**Checklist**
> Add Vaccination to data_visualization

- app/models/ability.rb
Foi retirado uma permission que estava duplicada. 
Rodar a aplicação e testar se as permissions de citymanager continuam as mesmas.
Comportamento normal da API. 
**Checklist**
> Removendo permissões de city manager duplicadas

- app/controllers/registration_controller.rb
- config/application.rb
Corrige timezone do rails.<br>
Da mesma forma na issue #370 
Timezone correta
**Checklist**
> Fix timezone

- app/controllers/rumors_controller.rb
- app/models/ability.rb
- app/models/app.rb
- app/models/rumor.rb
- app/serializers/rumor_serializer.rb
- db/migrate/20220211004034_add_app_references_to_rumors.rb
- db/schema.rb
**Descrição**
Foi concluído o CRUD de rumor e adicionada a relação com o app_id.
Testar as rotas get, update e delete dos rumores.
A rota get deve filtrar os rumores de acordo com o app_id.
Apenas administradores podem editar e deletar rumores.
> Atualização dos rumores

- app/controllers/doses_controller.rb
- app/models/dose.rb
- db/migrate/20220226004323_change_date_format_in_dose.rb
- db/schema.rb
Adiciona atributos nas models e serializers para o app poder consumir a partir das rotas
Rodar migrations e testar junto da branch `feature/thirdDose` no app.
Vacinas e doses funcionando
**Checklist**
> Fix vaccines/doses

- app/models/survey.rb
- app/serializers/user_serializer.rb
Corrige questionário enviado ao go.Data na model de Survey e altera atributos do serializer de User.
Ainda não há o PR do app aberto
Serializer do User e model Survey corrigidos
**Checklist**
> Fix user serializer and survey questionnaire

- app/controllers/rumors_controller.rb
- app/models/dose.rb
- app/serializers/dose_serializer.rb
- app/serializers/rumor_serializer.rb
- app/serializers/user_serializer.rb
- db/migrate/20220428155059_add_latitude_and_longitude_to_rumor.rb
- db/schema.rb
Realiza deploy da development.<br>
Abrir app e verificar se está tudo funcionando.
Servidor atualizado.
**Checklist**
> Deploy Development

- app/controllers/rumors_controller.rb
- app/models/rumor.rb
- app/models/user.rb
- app/serializers/content_serializer.rb
- app/serializers/rumor_serializer.rb
- db/migrate/20220705021742_add_user_to_rumors.rb
- db/schema.rb
Adiciona usuário aos rumores, migração e relações.<br>
Abrir o painel e testar na tela de Rumores.
Relacionar o rumor com o usuário que o criou
**Checklist**
> Add user to rumor

- spec/examples.txt
- spec/models/group_manager_team_spec.rb
Adicionado testes da função is_permitted?  da classse GroupManagerTeam<br>
(disciplina de testes de software)
**Checklist**
>  Adicionado testes da função is_permitted? da classse GroupManagerTeam

- app/controllers/admins_controller.rb
- app/controllers/rumors_controller.rb
- app/controllers/surveys_controller.rb
- app/controllers/users_controller.rb
- app/models/ability.rb
- app/models/user.rb
- app/serializers/user_for_ranking_serializer.rb
- app/serializers/user_ranking_serializer.rb
- config/cronotab.rb
- config/routes.rb
Adiciona rotina de ranking.<br>
Verificar ranking sem realizar report no dia e depois realizar report e verificar novamente.
Campo streak sendo atualizado todos os dias.
**Checklist**
> Add ranking routine

- app/models/flexible_answer.rb
- app/serializers/flexible_answer_serializer.rb
**Descrição**
- Adicionando report type a api de integração
> adding report type field to integration api

- app/models/flexible_form_version.rb
**Descrição**
Ajustando extracao dos campos do formulario dado que agora eles podem vir dentro do atributo "questions".
> ajustando para novo contrato flexible_form

- .github/workflows/development.yaml
**Descrição**
Ajusta a action de deploy dev para restartar o servico web. Apenas o pull não reflete as mudanças automaticamente.
**Como testar**
Ao executar o merge na branch development, verifique se a alteração surtiu efetivo.
**Resultados esperados**
Que ao efetuar o merge em development automaticamente as alterações sejam refletidas.
**Checklist**
> feat: adjust deploy dev action
