ProEpiDesenvolvimento/guardioes-api

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
**Descrição**
Conserta erros de ortografia no documento de código de conduta e contribuição<br>
**Checklist**
> Fix typos in CODE_OF_CONDUCT and CONTRIBUTING

- app/controllers/surveys_controller.rb
- config/environments/development.rb
- config/environments/production.rb
Esse PR adiciona cache nas queries de mapa, fazendo com que o tempo de resposta para o usuário da API seja diminuida.
Esse PR conserta a issue [37 do guardioes-app](https://github.com/proepidesenvolvimento/guardioes-app/issues/37) e é parte da #50.
**Checklist**
> Caching map query

- app/controllers/surveys_controller.rb
This pull request resolves the [issue #31](https://github.com/proepidesenvolvimento/guardioes-app/issues/31). It modifies the survey_controller so that the user can't report more than 2 differents surveys in a day.<br>
**Checklist**
> Limit surveys

- app/controllers/messages_controller.rb
- app/controllers/symptoms_controller.rb
- app/controllers/syndromes_controller.rb
- app/models/survey.rb
- app/models/symptom.rb
- app/models/syndrome.rb
- app/serializers/symptom_serializer.rb
Conserta problemas que atrapalhavam o update e delete de sindromes e sintomas, da issue #[96](https://github.com/proepidesenvolvimento/guardioes-api/issues/96).
Melhora o retorno para as surveys de forma a faze-lo mais fácil de se usar no front-end, sem preprocessamento, associado a issue #98.
**Checklist**
> Fix syndrome and symptom delete and update, enhance survey return

- app/controllers/groups_controller.rb
- app/models/group.rb
- app/serializers/group_serializer.rb
- db/migrate/20200812142255_add_group_manager_to_groups.rb
- db/migrate/20200812152255_remove_twitter_and_id_code_from_groups.rb
- db/schema.rb
Esse PR faz as seguintes alterações no modelo de grupos:
- Todos os grupos agora pertencem a um group manager.
- O twitter de um grupo é definido recursivamente como era antes, porém o dono desse twitter não é mais o próprio grupo e sim o seu group manager.
- O `require_id` e `id_code_length`, que guardavam informações sobre o código de identificação para um usuário registrando um grupo agora são delegados aos group_managers, como é o twitter.
- Conserta problema em que os dados CEP, endereço, codigo, email e telefone de um grupo não eram guardados.
Nenhuma dessas alterações alteram nenhum aspecto do funcionamento externo da API. Todas as rotas retém exatamente a mesma funcionalidade.
**Checklist**
> Resolve group system problems

- app/controllers/contents_controller.rb
No método de index para conteudos tem uma validação que restringe a apenas User terem acesso ao endpoint e quando formos fazer uso disso no Painel de controle precisamos de que os Admins também tenham acesso por isso fiz com que o index seja renderizado para os dois ;<br>
**Checklist**
> Add user type select to content index

- app/controllers/users_controller.rb
- app/serializers/household_serializer.rb
- app/serializers/user_serializer.rb
- db/migrate/20200901022156_add_policy_to_users.rb
- db/schema.rb
Adiciona a coluna policy_version no user em formato inteiro (versão de compilação) para o manuseio do consentimento de termos e políticas do app. Também adiciona a data de criação do usuário e do household para facilitar e corrigir bugs nos cálculos da tela Diário do app.<br>
Corrige a issue: #149 . <br> 
**Checklist**
> Adding privacy policy version and created_at date to User object

- app/controllers/admin_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/surveys_controller.rb
- app/models/user.rb
- app/serializers/message_serializer.rb
- app/serializers/user_serializer.rb
- db/migrate/20200624190816_create_messages.rb
- db/migrate/20200905020549_add_streak_to_user.rb
- db/schema.rb
Esse PR cria a lógica na API das mensagens de feedback para usuários que reportarem em dias consecutivos. Há uma mensagem para cada 3 dias, feita pela equipe de comunicação que pode ser encontrada [aqui](https://docs.google.com/document/d/19iZQq1naWkccxP9KuHeaEyDnhlcj-_IeV4mccjFzTRM/edit), que será cadastrada no banco de dados após as mudanças subirem para produção. Para acessar/criar/editar uma mensagem de feedback pode ser usado as rotas já existentes na API para a model mensagem. Para criar basta apenas criar com o atributo "feedback_message" dentro de "message" no JSON. 
Foi editado a model do usuário para que seja possível guardar os dias consecutivos reportados através do atributo STREAK com valor padrão igual a 1 para todos os usuários inicialmente. Esse valor …
> Creates the feedback messages for consecutives reports

- app/models/user.rb
Esse PR remove dependências de deletar um `user` para com `school_unit`.
Conserta bug #169.
**Checklist**
> Remover dependências ao deletar um user para com school_unit.

- app/models/survey.rb
**Os seguintes campos serão adicionados**
- `user_country`
- `user_city`
- `user_state`
- `birthdate`
- `risk_group`
**Os seguintes campos serão alterados:**
- `latitude`: Com distancias aleatórias de até 30 metros do seu local original, por questões de integridade de privacidade.
- `longitude`: Com distancias aleatórias de até 30 metros do seu local original, por questões de integridade de privacidade.
- `group`: diversas confusões foram causadas pela relação entre essa campo e `group`, portanto os dados do antigo `enrolled_in` vão aparecer aqui agora, caso `group` seja nulo.
**Os seguintes campos serão removidos:**
- `enrolled_in`: diversas confusões foram causadas pela relação entre essa campo e `group`, portanto os dados antigamente aqui vão para `group`, caso …
> Alteração de formato de dados survey enviados para elasticsearch

- app/models/survey.rb
- config/puma.rb
Adiciona o nome do household no novo feature de surveys em csv e aumenta o tempo de timeout do rails para impedir que a response ê timeout antes de carregar todos os dados necessários.
*100,000 surveys do csv = 1 minuto de processemento*
**Checklist**
> Add household name to csv data and increase response timeout range

- app/controllers/households_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/surveys_controller.rb
- app/models/user.rb
- app/serializers/household_serializer.rb
- app/serializers/message_serializer.rb
- db/migrate/20201020203908_add_day_to_messages.rb
- db/migrate/20201021181235_add_streak_to_household.rb
- db/schema.rb
Este PR melhora a gamificação do app. Agora não é mais necessário salvar as mensagens de feedback em ordem no banco. É possível salvar elas com um novo atributo "day"(inteiro) que significa em qual dia ela irá aparecer. É necessário se atentar para que não haja duas mensagens para o mesmo dia, pois se houver irá retornar apenas a primeira mensagem.<br>
**Exemplo**
Caso eu queira criar uma mensagem que apareça no décimo dia consecutivo de report do usuário eu preciso criar a seguinte mensagem:
{ "message": { "feedback_message": "Conteudo da mensagem aqui", "day": 10 } } 
Caso eu queira criar uma mensagem padrão:
{ "message": { "feedback_message": "Conteudo da mensagem aqui", "day": -1 } } . Day = -1 significa que essa mensagem é uma mensagem padrão e irá ser escolhida nos …
> Melhora a feature de gamificação

- app/models/survey.rb
**Descrição**<br
Esse PR remove a variação da latitude e longitude dos surveys no elasticsearch, assim também manda esses dois dados como foram recebidos, sem limitações de decimal etc.<br>
> Remove offset from latitude and longitude of surveys on elasticsearch

- app/controllers/syndromes_controller.rb
- app/models/syndrome.rb
- app/serializers/syndrome_serializer.rb
- db/migrate/20201118225337_add_app_id_to_syndromes.rb
- db/schema.rb
This PR adds the attribute app_id to syndromes. It was generated a migration to add, edited the controller to return only syndromes from the user's app_id and to create a syndrome with a specific app_id. It was also edited the serializer to return the app_id and the model to create the relationship between apps and syndromes. <br>
**Checklist**
> Adds the app_id to syndromes

- app/controllers/group_managers_controller.rb
Este PR deleta uma linha no método destroy do group_manager controller. Esta linha retorna um erro quando o group_manager não possui um grupo. Como ela é apenas um find e não possui finalidade aparente e como é possível existir um group_manager sem grupo, a remoção desta linha se faz necessária.<br>
Delete um group_manager sem grupo.
Group_manager precisa ser deletado.
> Conserta erro ao deletar gerente de instituição

- app/controllers/users_controller.rb
- app/models/user.rb
Esse PR resolve o problema da busca de usuários do Painel de Gerenciamento. Agora os usuários são retornados de acordo com o app_id do usuário logado no painel.
Resolve a issue [#155](https://github.com/proepidesenvolvimento/guardioes-web/issues/155) do repositório guardioes-web.
Para resolver completamente a issue citada acima, é necessário realizar adicionar um filtro para o caso de GroupManager, para a busca retornar apenas os usuários que são daquela instituição.
> Query user by app_id

- app/controllers/pre_registers_controller.rb
- app/serializers/pre_register_serializer.rb
- db/migrate/20201202024839_add_index_to_pre_registers.rb
Este PR retorna o email no GET de pre_register, deixa o email como único no banco de dados e modifica a função do mailer chamada pela api.<br>
1) Verifique se o email está sendo retornado ao dar um GET nos pre_registers
2) Tente criar um pre_register com um email já cadastrado e falhe
Obs.: não esqueça de rodar rails db:migrate
1) O email precisa ser retornado
2) Não deve ser possível cadastrar um email já cadastrado
**Checklist**
> Conserta alguns pontos do pré registro

- app/controllers/registration_controller.rb
Como o atributo vigilance_syndromes do group_manager é default = "", ocorre um erro ao tentar salvar o objeto com esse valor, pois ele precisa ser como padrão = []. Então antes de salvar esse atributo é setado como [] para evitar esse erro. Não é possível criar um group_manager com valores setados para o atributo vigilance_syndromes, mas não é necessário atualmente, devido a página exclusiva para a vigilância ativa.  <br>
Tente criar um group_manager, tanto pelo insomnia/postman quanto pelo painel web.
Modifique as síndromes na página de vigilância ativa.
É esperado que o group_manager seja criado corretamente.
É esperado que as síndromes sejam modificadas corretamente na página de vigilância ativa.
> Conserta erro ao criar um group_manager

- Gemfile.lock
- app/serializers/household_serializer.rb
- app/serializers/user_serializer.rb
Foi removido o atributo ```picture``` das serializers de User e Household porque não são mais utilizados pelo app.<br>
Rodar a api e dar get no User.
Não possuir mais a coluna picture nos métodos GET.
**Checklist**
> Hide picture column to User and Household

- app/controllers/group_managers_controller.rb
- app/models/survey.rb
- db/migrate/20210227165442_add_go_data_user_id.rb
- db/schema.rb
Gera a migration para criar o campo para persistir o id do usuário godata.
Ativa o surto reportado toda vez antes de enviar um report para o godata
> Active outbreak before report case

- app/controllers/city_managers_controller.rb
- app/mailers/city_manager_mailer.rb
- app/views/city_manager_mailer/reset_password_email.html.erb
- config/routes.rb
- db/migrate/20210312212517_add_aux_code_to_city_managers.rb
- db/schema.rb
Adiciona os métodos e rotas para recuperação de senha do City Manager. Esse PR também fecha a issue [#243](https://github.com/proepidesenvolvimento/guardioes-web/issues/243) do repo `guardioes-web`.<br>
Abra o painel do ```guardioes-web``` e escolha a opção de "Esqueci a senha" no login para digitar um email de City Manager e receber o código por email.
Ser possível trocar a senha após ter esquecido.
**Checklist**
> Add City Managers reset password

- app/models/survey.rb
- app/models/user.rb
- db/schema.rb
Corrige dois bugs possíveis na hora de criar uma survey: o primeiro é quando a gem geocode não consegue achar o local pela latitude e longitude, o segundo é quando não há nenhuma mensagem cadastrada de retorno.<br>
Enviar uma Survey com latitude: 0 e longitude: 0 não deve retornar erros.
Na falta de mensagem de feedback, uma padrão deve ser mostrada.
Não retornar erro nos dois casos.
**Checklist**
> Fix geocode gem and feedback_message on Survey model

- app/controllers/city_managers_controller.rb
- app/models/ability.rb
- db/migrate/20210525001628_add_deleted_at_to_city_managers.rb
- db/schema.rb
Adiciona a migration de deleted_at para os CityManagers funcionarem corretamente com a gem `paranoia`.<br>
Teste os métodos GET, POST e PATCH dos City Managers.
Não receber mais erros nos métodos: GET, POST e PATCH
**Checklist**
> Add CityManager deleted_at migration

- db/migrate/20210622214806_update_require_id.rb
- db/schema.rb
Foi mudado o tipo da coluna require_id da tabela de group_managers do banco de dados para poder permitir que o título do código de identificação no app fosse algo que os group_managers pudessem alterar.
Criar um group_managers com o require_id como string e verificar se foi salvo. Outro ponto é testar as rotas se o create/update também alteram corretamente. Para este ultímo pode ser usado o web ou mesmo o postman.
A API deve ser capaz de guardar corretamente o valor em string, aceitar valor null e permiter alterações do tipo CRUD nas rotas. 
**Checklist**
> Mudando tipo da coluna require_id da tabela de group_managers de boolean para string

- app/controllers/data_visualization_controller.rb
Adiciona o GroupManagerTeam no método `metabase_urls` da data_visualization_controller.rb, para ele ter acesso as dashboards.<br>
Utilizar a rota `/data_visualization/metabase_urls` pelo Postman logado como GroupManagerTeam;
GroupManagerTeam receber as urls temporárias de dashboards.
**Checklist**
> Add GroupManagerTeam in metabase_urls

- app/controllers/users_controller.rb
Corrige os métodos `filtered_list` e `panel_list` na users_controller.rb para os GroupManagerTeams que não conseguiam ver os usuários pertencentes ao Grupo.<br>
Fazer login como GroupManagerTeam no Painel (`guardioes-web`);
Abrir o menu lateral 'Usuários';
Ver os usuários pertencentes a aquele grupo;
Utilizar a ferramenta de filtragem. 
Retornar usuários da mesma instituição dos GroupManagerTeams
**Checklist**
> Fix show Users for GroupManagerTeam

- app/controllers/data_visualization_controller.rb
- app/serializers/group_manager_team_serializer.rb
Adiciona relação `has_one: group_manager` no serializer do GroupManagerTeam para retornar o objeto do GroupManager inteiro na resposta. É necessário para o Painel.<br>
Dar GET na rota `/group_manager_teams` e ver o GroupManager correspondente ser retornado em cada GroupManagerTeam.
Ver o objeto do GroupManager ser retornado em cada GroupManagerTeam.
**Checklist**
> Fix GroupManagerTeam Serializer

- app/controllers/data_visualizations_controller.rb
- app/controllers/groups_controller.rb
- app/models/ability.rb
- app/models/group.rb
- app/models/group_manager_team.rb
- app/serializers/group_serializer.rb
- config/routes.rb
Corrige as permissões dos GroupManagerTeams para Groups e DataVisualizations.<br>
1. Abra o painel com o repo `guardioes-web` na branch `fix/groupManagerTeamsPermissions`;
2. Logue como uma Instituição que possua grupos;
3. Crie/edite dois GroupManagerTeams: Um com permissão para Grupos e Visualizações, outro com nenhuma das duas permissões;
4. Logue agora como Equipe de Instituição na primeira conta criada e teste as permissões nas abas de Grupos e Visualizações;
5. Logue agora como Equipe de Instituição na segunda conta criada e teste as mesmas permissões. 
A primeira conta deve conseguir ver as Visualizações e gerenciar Grupos. A segunda conta não deve conseguir fazer nenhuma das duas ações.
**Checklist**
> Fix GroupManagerTeams permissions

- app/controllers/surveys_controller.rb
- app/controllers/syndromes_controller.rb
- app/models/survey.rb
- app/serializers/syndrome_serializer.rb
- db/migrate/20210811141836_add_threshold_score_to_syndromes.rb
- db/schema.rb
Esse pull request adapta o código para que a API receba e persista o valor de um limiar e use esse recurso para filtrar os surveys que tenham um score acima ou igual desse limite.
Crie/Atualize o valor do campo threshold_score de uma syndrome e verifique a persistência. Crie um survey e veja printando o score e o o threshold e confirmando a comparação. 
é esperado que o sistema não retorne sindromes que tenham um score menor que o limiar com o survey que o usuário enviou.
**Checklist**
> Adicionar campo de limiar e atualizando cálculo do score de um survey

- app/controllers/groups_controller.rb
Foi trocado a ordem na função create da controller de groups. Agora o "@group" é gerado antes de chamar a função validate_group_manager_permissions.
Chame a rota create de groups normalmente e verifique se os groups são criado corretamente.
**Checklist**
> Fixing bug when a group is created

- app/models/survey.rb
- app/serializers/survey_for_map_serializer.rb
Foi alterada a função que calcula o offset das coordenadas de modo que não mostre a localização real do usuário no mapa. A função que calcula esse offset foi adicionada à serializaer SurveysForMapSerializer. 
Rode a aplicação, coloque prints na serializer SurveyForMapSerializer para comparar o antes e dps das coordenadas e por fim faça requisições na rota surveys/week para acionar os prints. Calculadoras de distância entre coordenadas na internet eralmente não dão a informação com a precisão necessária, portanto recomendo fazer um script em python para fazer esses calculos e verificar a distância.  
É esperado que o offset em linha reta fique entre 70 e 106 metros aproximadamente e que as localização fornecidas sejam …
> Adding offset to coordinates in surveyForMapSerializer

- app/models/group_manager_team.rb
- app/serializers/group_manager_serializer.rb
Foi removido a parte em que adicionava as groupManagerPermissions na Serializer a fim de diminuir o tamanho em bytes da resposta que ia ao front. Resposta essa que grande demais pode gerar bugs na aplicação e então por isso esses dados foram retirados. 
Logue como GroupManager e verificar se o GroupManager  permission está na response. Outro teste é com relação as funcionalidades padrões que envolvem tanto os GroupManager teams e essa informação não está sendo usada em alguma parte da aplicação ou se essa ação de retirar possa ter causado algum outro bug. Para essa parte é necessário andar pela aplicaçaõ e testando alguns casos que podem gerar bugs.
Espera-se que o site funcione normalmente, sem cair a página quando logue …
> Removing GroupManager permissions from response.

- app/controllers/households_controller.rb
Corrige a criação de households. Havia um @user.reindex que era utilizado pelo elasticsearch, que foi descontinuado. Isso causava um status de erro na criação.<br>
Criar household pelo app usando essa branch na api local; ou
Criar household pela rota disponível no Postman.
Ser possível criar households sem status de erro.
**Checklist**
> Fix households

- app/controllers/surveys_controller.rb
Corrige status HTTP ao já ter reportado Survey.<br>
1. Enviar Survey com usuário que não tenha reportado nenhuma vez (ver status 201)
2. Reportar Survey novamente (ver status 208 ao invés de 422)
Status correto ao reportar mais de uma vez
**Checklist**
> Fix survey HTTP status

- app/controllers/contents_controller.rb
- app/models/ability.rb
- app/models/content.rb
- app/models/group_manager.rb
- app/serializers/content_serializer.rb
- db/migrate/20220629023629_add_group_manager_to_contents.rb
- db/schema.rb
Foi adicionada a migração para adicionar o group_manager_id na tabela contents e criadas as relações nas models.<br>
Acessar o painel com a branch `add/gmContents` e testar com Administradores e Instituições a tela de Conteúdo.
Contextos diferentes de conteúdos para Administradores e Instituição
**Checklist**
> Add migration and relations for group_manager and content

- app/serializers/flexible_answer_serializer.rb
Este PR modifica o arquivo `flexible_answer_serializer.rb` para ajustar a estrutura do retorno do método `signal`, encapsulando o resultado dentro de um objeto `_embedded` com uma chave `signals`.
O objetivo desta alteração é garantir que o resultado do método `signal` esteja conforme o padrão esperado para respostas que incluem sinais de sistemas externos. Ao encapsular `result` dentro de um objeto `_embedded` com uma chave `signals`, o retorno passa a estar mais alinhado com as práticas de organização de dados estruturados, facilitando a integração e o consumo por parte de outros serviços e aplicações.
Esta mudança afeta a forma como os dados de sinais são serializados, potencialmente impactando qualquer integração que consuma esta API. É importante garantir que todos os consumidores do …
> fix: update to match app contract

- app/controllers/flexible_answers_controller.rb
Esta é uma mudança simples que remove a lógica que só permitia que os eventos de sinais dos usuários marcados com "is_vbe" sejam encaminhados para o Ephem via integração.
Após a remoção, qualquer usuário cadastrado que envie um sinal, este sinal será enviado para o Ephem (https://vbe.sds.unb.br/)
Após a remoção, qualquer usuário cadastrado que envie um sinal, este sinal será enviado para o Ephem (https://vbe.sds.unb.br/)
**Checklist**
> feat: removendo regra
